[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solarc-eclipse"
dynamic = ["version"]
authors = [
    {name = "James McKevitt", email = "jm2@mssl.ucl.ac.uk"},
]
description = "ECLIPSE: Emission Calculation and Line Intensity Prediction for SOLAR-C EUVST"
readme = "README.md"
license = {text = "Contact for permission"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "numpy",
    "astropy",
    "ndcube",
    "specutils",
    "scipy",
    "matplotlib",
    "joblib",
    "tqdm",
    "dill",
    "pyyaml",
    "reproject",
    "sunpy[all]",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
    "mypy",
]

[project.scripts]
eclipse = "euvst_response.cli:main"
solarc-eclipse = "euvst_response.cli:main"
synthesise-spectra = "euvst_response.synthesis_cli:main"
synthesise_spectra = "euvst_response.synthesis_cli:main"

[project.urls]
Homepage = "https://github.com/jamesmckevitt/eclipse"
Repository = "https://github.com/jamesmckevitt/eclipse"

[tool.setuptools.packages.find]
include = ["euvst_response*"]

[tool.setuptools.dynamic]
version = {attr = "euvst_response.__version__"}

[tool.setuptools.package-data]
euvst_response = ["data/**/*"]
